import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import { CenterPopupProvider } from "../context/CenterPopupContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fanith",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  verification: {
    google: "NuzrfCBkMnKxUWqtc90k75r1a0AmcO4Fq7sfQNDU0XM",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google tag (gtag.js) */}
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-WDBDHCKBRE" strategy="afterInteractive" />
        <Script id="ga4" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-WDBDHCKBRE');
          `}
        </Script>
        {/* Microsoft Clarity Tag */}
        <Script type="text/javascript">
          {`
            (function(c,l,a,r,i,t,y){
            c[a] = c[a] || function () { (c[a].q = c[a].q || []).push(arguments) };
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "v4c5y9q2hd");
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CenterPopupProvider>
          <Header />
          <main className="pt-16">{children}</main>
          <Footer />
          <ToastContainer />
        </CenterPopupProvider>
      </body>
    </html>
  );
}
